enum SectionName {
  // ===================Umlazi [Area 1-27]===================
  aSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  aaSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  bSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  bbSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  cSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  ccSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  dSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  eSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  fSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  gSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  hSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  jSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  kSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  lSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  mSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  nSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  pSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  qSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  rSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  sSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  uSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  vSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  wSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  malukaziUmlaziDurbanKwaZuluNatalSouthAfrica,
  ySectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  zSectionUmlaziDurbanKwaZuluNatalSouthAfrica,
  philaniUmlaziDurbanKwaZuluNatalSouthAfrica,

  // ===================Institutions [Area 28-30]===================
  mutDurbanKwaZuluNatalSouthAfrica,
  dutDurbanKwaZuluNatalSouthAfrica,
  howardCollegeCampusUKZNDurbanKwaZuluNatalSouthAfrica,

  // ===================Mayville [Area 31-37]===================
  catoCrestMayvilleDurbanKwaZuluNatalSouthAfrica,
  catoManorMayvilleDurbanKwaZuluNatalSouthAfrica,
  richviewMayvilleDurbanKwaZuluNatalSouthAfrica,
  masxhaMayvilleDurbanKwaZuluNatalSouthAfrica,
  bonelaMayvilleDurbanKwaZuluNatalSouthAfrica,
  nsimbiniMayvilleDurbanKwaZuluNatalSouthAfrica,
  galwayMayvilleDurbanKwaZuluNatalSouthAfrica,

  // ===================Sydenham [Area 38-42]===================
  foremanSydenhamDurbanKwaZuluNatalSouthAfrica,
  kennedySydenhamDurbanKwaZuluNatalSouthAfrica,
  palmetSydenhamDurbanKwaZuluNatalSouthAfrica,
  burnwoodSydenhamDurbanKwaZuluNatalSouthAfrica,
  sydenhamHeightSydenhamDurbanKwaZuluNatalSouthAfrica,
  threeRandSydenhamDurbanKwaZuluNatalSouthAfrica,

  // ===================Durban Central [Area 43-46]===================
  glenwoodDurbanCentralDurbanKwaZuluNatalSouthAfrica,
  bereaDurbanCentralDurbanKwaZuluNatalSouthAfrica,
  southBeachDurbanCentralDurbanKwaZuluNatalSouthAfrica,
  masgraveDurbanCentralDurbanKwaZuluNatalSouthAfrica,

  // ===================Nanda [Area 47+]===================

  bhambayiNandaDurbanKwaZuluNatalSouthAfrica,
  ezimangweniNandaDurbanKwaZuluNatalSouthAfrica,
  dikweNandaDurbanKwaZuluNatalSouthAfrica,
  mshayazafeNandaDurbanKwaZuluNatalSouthAfrica,
  jackportNandaDurbanKwaZuluNatalSouthAfrica,
  ohlangeNandaDurbanKwaZuluNatalSouthAfrica,
  africaNandaDurbanKwaZuluNatalSouthAfrica,
  congoNandaDurbanKwaZuluNatalSouthAfrica,
  maotiNandaDurbanKwaZuluNatalSouthAfrica,
  newtownANandaDurbanKwaZuluNatalSouthAfrica,
  newtownBNandaDurbanKwaZuluNatalSouthAfrica,
  kaGNandaDurbanKwaZuluNatalSouthAfrica,
  matendeniNandaDurbanKwaZuluNatalSouthAfrica,
  mtshebheniNandaDurbanKwaZuluNatalSouthAfrica,
  zinkawiniNandaDurbanKwaZuluNatalSouthAfrica,
  tafuleniNandaDurbanKwaZuluNatalSouthAfrica,
  ngoqokaziNandaDurbanKwaZuluNatalSouthAfrica,
  matikweNandaDurbanKwaZuluNatalSouthAfrica,
}
